[project]
name = "author-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenneth Packard", email = "kenpack6@byu.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "deepstylometry",
]

[project.optional-dependencies]
cuda = [
    "torch",
    "torchvision",
    "deepstylometry[cuda]",
]
cu124 = [
    "torch",
    "torchvision",
    "deepstylometry[cu124]",
]

[project.scripts]
author-prediction = "author_prediction:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "DeepStylometry",
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv.sources]
deepstylometry = { workspace = true, editable = true }
torch = [
    { index = "pytorch-cu124", extra = "cuda", marker = "sys_platform != 'darwin'" },
    { index = "pytorch-cu124", extra = "cu124", marker = "sys_platform != 'darwin'" },
]
torchvision = [
    { index = "pytorch-cu124", extra = "cuda", marker = "sys_platform != 'darwin'" },
    { index = "pytorch-cu124", extra = "cu124", marker = "sys_platform != 'darwin'" },
]

[dependency-groups]
server = [
    "fastapi>=0.141.1",
]
